export default {
  fullHeadline: 'Register now for {price}.',
  headline: 'Register now for',
  logoUrl: 'https://prod.drive-now-content.com/fileadmin/user_upload_de/assets/registration/reg-head-img.png',
  price: '€29',
  segments: [
    {
      elements: [
        {
          currentTenant: 'DE',
          id: 'tenantSelector',
          infotext: 'Please select the country where you will mainly use DriveNow.',
          options: [
            { value: 'DE', text: 'Germany' },
            { value: 'GB', text: 'United Kingdom' },
            { value: 'AT', text: 'Austria' },
            { value: 'DK', text: 'Denmark' },
            { value: 'SE', text: 'Sweden' },
          ],
          type: 'tenantSelector',
        }, {
          error: 'Please enter a valid e-mail address',
          id: 'email',
          infotext: 'Your e-mail address serves as login into the Customer Area.',
          label: 'E-mail address',
          style: {
            width: 'double',
          },
          width: 'double',
          type: 'input',
          validation: {
            required: true,
            pattern: 'email',
          },
        }, {
          error: 'Please enter a valid password',
          id: 'password',
          infotext: 'Your password serves as login into the Customer Area. The minimum of eight and maximum of fifteen characters needs to contain at least one letter (a-z) and at least two numbers (0-9) or special characters (-,_,#,(,),@,§,!,%,&,$). The password can not contain å, ä, ö.',
          label: 'Set password',
          type: 'password',
          validation: {
            required: true,
            pattern: 'password',
          },
        }, {
          error: 'Enter PIN consisting of 4 digits',
          id: 'pin',
          infotext: 'You will need your 4-digit PIN to identify yourself when you arrive at the car.',
          label: 'Please choose a PIN for login in the car (4 digits)',
          type: 'pin',
          validation: {
            required: true,
            pattern: 'digits',
            length: 4,
          },
        }, {
          error: 'Please select a security question',
          id: 'securityQuestion',
          infotext: 'Use the security question to authenticate yourself at customer service. The answer must contain a minimum of 3 characters.',
          label: 'Security question',
          options: [
            { value: 'Favorite dish', text: 'Favorite dish' },
            { value: 'Favorite movie', text: 'Favorite movie' },
            { value: 'Mother`s maiden name', text: 'Mother`s maiden name' },
          ],
          type: 'select',
          validation: {
            required: true,
          },
        }, {
          error: 'Please enter security answer',
          id: 'securityAnswer',
          infotext: 'Use the security question to authenticate yourself at customer service. The answer must contain a minimum of 3 characters.',
          label: 'Answer',
          type: 'input',
          validation: {
            required: true,
            minLength: 3,
            maxLength: 30,
          },
        },
      ],
      header: 'Login',
      id: 'loginDetails',
      section: 1,
      statusIconUrl: 'https://de.drive-now.com/static/drivenow/img/dynreg/logindetails.png',
      statusIconUrlActive: 'https://de.drive-now.com/static/drivenow/img/dynreg/logindetails_active.png',
      statusbar: true,
      statusbarText: 'Login',
    },
    {
      header: 'Contact data',
      id: 'primaryDetails',
      section: 2,
      statusIconUrl: 'https://de.drive-now.com/static/drivenow/img/dynreg/primarydetails.png',
      statusIconUrlActive: 'https://de.drive-now.com/static/drivenow/img/dynreg/primarydetails_active.png',
      statusbar: true,
      statusbarText: 'Contact',
    },
    {
      header: 'Payment data',
      id: 'paymentDetails',
      section: 3,
      statusIconUrl: 'https://de.drive-now.com/static/drivenow/img/dynreg/paymentdetails.png',
      statusIconUrlActive: 'https://de.drive-now.com/static/drivenow/img/dynreg/paymentdetails_active.png',
      statusbar: true,
      statusbarText: 'Payment',
    },
    {
      header: 'Driving licence',
      id: 'driversLicense',
      section: 4,
      statusIconUrl: 'https://de.drive-now.com/static/drivenow/img/dynreg/driverslicense.png',
      statusIconUrlActive: 'https://de.drive-now.com/static/drivenow/img/dynreg/driverslicense_active.png',
      statusbar: true,
      statusbarText: 'Licence',
    },
    {
      header: 'Fifth Segment',
      id: 'FifthSegment',
      section: 5,
      statusIconUrl: 'https://de.drive-now.com/static/drivenow/img/dynreg/driverslicense.png',
      statusIconUrlActive: 'https://de.drive-now.com/static/drivenow/img/dynreg/driverslicense_active.png',
      statusbar: true,
      statusbarText: 'Fifth Segment',
    },
  ],
};
